name: Firebase Deploy

on:
  push:
    branches:
      - development
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Firebase project dynamically
      - name: Set Firebase environment
        run: |
          BRANCH="${GITHUB_REF##*/}"

          echo "Branch: $BRANCH"

          if [[ "$BRANCH" == "development" ]]; then
            echo "FIREBASE_PROJECT=pmarena-dev" >> $GITHUB_ENV
            echo "FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT_PMARENA_DEV }}" >> $GITHUB_ENV

          elif [[ "$BRANCH" == "staging" ]]; then
            echo "FIREBASE_PROJECT=pmarena-staging" >> $GITHUB_ENV
            echo "FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT_PMARENA_STAGING }}" >> $GITHUB_ENV

          elif [[ "$BRANCH" == "main" ]]; then
            echo "FIREBASE_PROJECT=pmarena-prod" >> $GITHUB_ENV
            echo "FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT_PMARENA_PROD }}" >> $GITHUB_ENV

          else
            echo "Unknown branch"
            exit 1
          fi

      # Build app
      - run: npm ci && npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      # Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ env.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ env.FIREBASE_PROJECT }}